# .gitlab-ci.yml

# 定义一个名为 "build" 的作业
build:
  # 使用 Node.js 官方镜像作为运行环境
  image: node:19

  # 作业执行的脚本命令
  script:
      # 检查是否已经存在全局的 pnpm 缓存
    - |
      if [ ! -d /cache/pnpm-store ]; then
        npm install -g pnpm
        pnpm config set store-dir /cache/pnpm-store
      else
        echo "Using cached pnpm store"
      fi

    # 使用 pnpm 安装依赖
    - pnpm install

    # 运行 npm 脚本进行构建
    - npm run build

  # 定义作业的缓存策略，以提高构建速度
  cache:
    # 缓存 pnpm 的依赖目录，以避免重复安装依赖
    key: $CI_COMMIT_REF_SLUG
    paths:
      - /cache/pnpm-store/
      - node_modules/

# 添加其他作业或配置